// Code generated by "stringer -type=NodeType -linecomment"; DO NOT EDIT.

package kdd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidNode - -1]
	_ = x[RhsNode-0]
	_ = x[RuleNode-1]
	_ = x[SourceNode-2]
}

const _NodeType_name = "InvalidNodeRhsRuleSource"

var _NodeType_index = [...]uint8{0, 11, 14, 18, 24}

func (i NodeType) String() string {
	i -= -1
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
