// Code generated by "grammar -i=g.txt".

package parser

import (
	"github.com/PlayerR9/SlParser/lexer"
)

var (
	Lexer *lexer.Lexer
)

func init() {
	var builder lexer.Builder

	// TODO: Write here the logic for lexing a single token...

	Lexer = builder.Build()
}
