// Code generated by "grammar -i=g.txt".

package parser

//go:generate stringer -type=NodeType -linecomment

type NodeType int

const (
	/*SourceNode is the root of the AST.
	Node[SourceNode]
	*/
	SourceNode NodeType = iota // Source
)

// String implements the fmt.Stringer interface.
func (nt NodeType) String() string {
	return [...]string{
		"Source",
	}[nt]
}

// AreChildrenCritical checks whether the children of a node are critical depending on the type
// they have.
//
// A children is said to be critical if, when an error occurs, the entire processed should be stopped
// instead of continuing.
//
// Returns:
//   - bool: True if they are, false otherwise.
func (nt NodeType) AreChildrenCritical() bool {
	return nt != SourceNode
}
