// Code generated by SlParser. Do not edit.
package ebnf

import (
	"github.com/PlayerR9/grammar"
)

var (
	// Parser is the complete parser of the grammar.
	Parser *grammar.Parser[*Node, token_type]
)

func init() {
	Parser = grammar.NewParser(
		internal_lexer,
		internal_parser,
		ast_builder,
	)
}
