// Code generated by "stringer -type=PhaseType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhaseReduction-0]
	_ = x[PhasePrediction-1]
	_ = x[PhaseShifting-2]
	_ = x[PhaseCheckBranch-3]
}

const _PhaseType_name = "PhaseReductionPhasePredictionPhaseShiftingPhaseCheckBranch"

var _PhaseType_index = [...]uint8{0, 14, 29, 42, 58}

func (i PhaseType) String() string {
	if i < 0 || i >= PhaseType(len(_PhaseType_index)-1) {
		return "PhaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PhaseType_name[_PhaseType_index[i]:_PhaseType_index[i+1]]
}
