// Code generated by SlParser.
package test

// token_type is the type of a token.
type token_type int

const (
	etk_EOF token_type = iota
	
	ttk_Identifier
	ttk_OrExpr
	ttk_OrExpr1
	ttk_Rhs
	ttk_Rhs1
	ttk_Rule
	ttk_Rule1
	ttk_Source
	ttk_Source1
	
	ntk_CL_PAREN
	ntk_COLON
	ntk_LOWERCASE_ID
	ntk_OP_PAREN
	ntk_PIPE
	ntk_SEMICOLON
	ntk_UPPERCASE_ID
)

// String implements the Grammar.TokenTyper interface.
func (t token_type) String() string {
	return [...]string{
		"End of File",
		// Add here your custom token names.
	}[t]
}

// GoString implements the Grammar.TokenTyper interface.
func (t token_type) GoString() string {
	return [...]string{
		"etk_EOF",
		
		"ttk_Identifier",
		"ttk_OrExpr",
		"ttk_OrExpr1",
		"ttk_Rhs",
		"ttk_Rhs1",
		"ttk_Rule",
		"ttk_Rule1",
		"ttk_Source",
		"ttk_Source1",
		
		"ntk_CL_PAREN",
		"ntk_COLON",
		"ntk_LOWERCASE_ID",
		"ntk_OP_PAREN",
		"ntk_PIPE",
		"ntk_SEMICOLON",
		"ntk_UPPERCASE_ID",
	}[t]
}