// Code generated by EbnfParser.
package test

// TokenType is the type of a token.
type TokenType int

const (
	EtkEOF TokenType = iota 
	
	TtkAssignmentOp
	TtkAsteriskOp
	TtkClParen
	TtkClSquare
	TtkFor
	TtkIn
	TtkNewline
	TtkNumber
	TtkOpParen
	TtkOpSquare
	TtkRange
	TtkSpace
	TtkType
	TtkVariableId
	
	NtkID
	NtkSource
)

// String implements the Grammar.TokenTyper interface.
func (t TokenType) String() string {
	return [...]string{
		"End of File",
		// Add here your custom token names.
	}[t]
}

// GoString implements the Grammar.TokenTyper interface.
func (t TokenType) GoString() string {
	return [...]string{
		"EtkEOF",
		
		"TtkAssignmentOp",
		"TtkAsteriskOp",
		"TtkClParen",
		"TtkClSquare",
		"TtkFor",
		"TtkIn",
		"TtkNewline",
		"TtkNumber",
		"TtkOpParen",
		"TtkOpSquare",
		"TtkRange",
		"TtkSpace",
		"TtkType",
		"TtkVariableId",
		
		"NtkID",
		"NtkSource",
	}[t]
}
