// Code generated by SlParser.
package test

// token_type is the type of a token.
type token_type int

const (
	etk_EOF token_type = iota 
	
	ttk_AssignmentOp
	ttk_AsteriskOp
	ttk_ClParen
	ttk_ClSquare
	ttk_For
	ttk_In
	ttk_Newline
	ttk_Number
	ttk_OpParen
	ttk_OpSquare
	ttk_Range
	ttk_Space
	ttk_TypeId
	ttk_VariableId
	
	ntk_Source
)

// String implements the Grammar.TokenTyper interface.
func (t token_type) String() string {
	return [...]string{
		"End of File",
		// Add here your custom token names.
	}[t]
}

// GoString implements the Grammar.TokenTyper interface.
func (t token_type) GoString() string {
	return [...]string{
		"etk_EOF",
		
		"ttk_AssignmentOp",
		"ttk_AsteriskOp",
		"ttk_ClParen",
		"ttk_ClSquare",
		"ttk_For",
		"ttk_In",
		"ttk_Newline",
		"ttk_Number",
		"ttk_OpParen",
		"ttk_OpSquare",
		"ttk_Range",
		"ttk_Space",
		"ttk_TypeId",
		"ttk_VariableId",
		
		"ntk_Source",
	}[t]
}