// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EtInvalid - -1]
	_ = x[EtEof-0]
	_ = x[TtColon-1]
	_ = x[TtLowercaseId-2]
	_ = x[TtNewline-3]
	_ = x[TtSemicolon-4]
	_ = x[TtUppercaseId-5]
	_ = x[NtRhs-6]
	_ = x[NtRule-7]
	_ = x[NtRule1-8]
	_ = x[NtSource-9]
	_ = x[NtSource1-10]
}

const _TokenType_name = "EtInvalidEtEofTtColonTtLowercaseIdTtNewlineTtSemicolonTtUppercaseIdNtRhsNtRuleNtRule1NtSourceNtSource1"

var _TokenType_index = [...]uint8{0, 9, 14, 21, 34, 43, 54, 67, 72, 78, 85, 93, 102}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
