package generation

import (
	ggen "github.com/PlayerR9/go-generator/generator"
)

type LexerGen struct {
	PackageName string
}

func (g *LexerGen) SetPackageName(pkg_name string) {
	g.PackageName = pkg_name
}

var (
	LexerGenerator *ggen.CodeGenerator[*LexerGen]
)

func init() {
	tmp, err := ggen.NewCodeGeneratorFromTemplate[*LexerGen]("", lexer_templ)
	if err != nil {
		Logger.Fatalf("Error creating code generator: %s", err.Error())
	}

	LexerGenerator = tmp
}

const lexer_templ string = `// Code generated by SlParser.
package {{ .PackageName }}

import (
	gr "github.com/PlayerR9/grammar/grammar"
	grlx "github.com/PlayerR9/grammar/lexer"
)

var (
	// Lexer is the lexer of the grammar.
	Lexer *grlx.Lexer[TokenType]
)

func init() {
	lex_one := func(l *grlx.Lexer[TokenType]) (*gr.Token[TokenType], error) {
		// Lex here...
	
		panic("Implement me!")
	}

	Lexer = grlx.NewLexer[TokenType](lex_one)
}
`
