// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package parsing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EttInvalid - -1]
	_ = x[EttEOF-0]
	_ = x[TttListComprehension-1]
	_ = x[TttPrintStmt-2]
	_ = x[TttNewline-3]
	_ = x[NttSource-4]
	_ = x[NttSource1-5]
	_ = x[NttStatement-6]
}

const _TokenType_name = "EttInvalidEttEOFTttListComprehensionTttPrintStmtTttNewlineNttSourceNttSource1NttStatement"

var _TokenType_index = [...]uint8{0, 10, 16, 36, 48, 58, 67, 77, 89}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
