// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package parsing

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EttEOF-0]
	_ = x[TttListComprehension-1]
	_ = x[TttPrintStmt-2]
	_ = x[TttNewline-3]
}

const _TokenType_name = "EttEOFTttListComprehensionTttPrintStmtTttNewline"

var _TokenType_index = [...]uint8{0, 6, 26, 38, 48}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
