package internal

import (
	kdd "github.com/PlayerR9/SlParser/kdd"
	gers "github.com/PlayerR9/go-errors"
	"github.com/PlayerR9/go-generator"
)

// ASTGen is a generator for the AST.
type ASTGen struct {
	// PackageName is the name of the package.
	PackageName string

	// Ast is the list of candidates for the node types in the AST.
	Ast []string
}

// SetPackageName implements the generator.PackageNameSetter interface.
func (g *ASTGen) SetPackageName(pkg_name string) {
	if g == nil {
		return
	}

	g.PackageName = pkg_name
}

// NewASTGen creates a new ASTGen with the given tokens.
//
// Parameters:
//   - table: The information about the AST.
//
// Returns:
//   - *ASTGen: the ASTGen. Never returns nil.
func NewASTGen(table map[*kdd.Node]*Info) *ASTGen {
	candidates := CandidatesForAst(table)

	gen := &ASTGen{
		Ast: candidates,
	}

	return gen
}

var (
	// ASTGenerator is the generator for the AST.
	ASTGenerator *generator.CodeGenerator[*ASTGen]
)

func init() {
	var err error

	ASTGenerator, err = generator.NewCodeGeneratorFromTemplate[*ASTGen]("ast", ast_templ)
	gers.AssertErr(err, "generator.NewCodeGeneratorFromTemplate[*ASTGen](%q, ast_templ)", "ast")
}

// ast_templ is the template for the AST.
const ast_templ = `// Code generated by SlParser. Do not edit.
package {{ .PackageName }}

import (
	"errors"

	"github.com/PlayerR9/SlParser/ast"
	"github.com/PlayerR9/SlParser/grammar"
)

// NodeType is the type of a node.
type NodeType int

const (
	/*InvalidNode represents an invalid node.
	Node[InvalidNode]
	*/
	InvalidNode NodeType = iota - 1 // Invalid {{ range $index, $value := .Ast }}

	/*{{ $value }}Node is [...].
	Node[{{ $value }}Node]
	*/
	{{ $value }}Node // {{ $value }}
	{{- end }}
)

var (
	ast_maker ast.AstMaker[*Node, TokenType]
)
	
func init() {
	ast_maker = make(ast.AstMaker[*Node, TokenType])

	// TODO: Add here your own custom rules...
	{{ range $index, $value := .Ast }}
	ast_maker[{{ $value }}] = func(tk *grammar.ParseTree[TokenType]) (*Node, error) {
		children := tk.GetChildren()
		if len(children) == 0 {
			return nil, errors.New("expected at least one child")
		}

		// TODO: Complete this function...

		node := NewNode(tk.Pos(), {{ $value }}Node, "")
		return node, nil
	}
	{{- end }}
}`
