// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidTk - -1]
	_ = x[ExtraTk-0]
	_ = x[TerminalTk-1]
	_ = x[NonterminalTk-2]
}

const _TokenType_name = "InvalidTkExtraTkTerminalTkNonterminalTk"

var _TokenType_index = [...]uint8{0, 9, 16, 26, 39}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
