// Code generated by "stringer -type=TokenType -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExtraTk-0]
	_ = x[TerminalTk-1]
	_ = x[NonterminalTk-2]
}

const _TokenType_name = "EtTtNt"

var _TokenType_index = [...]uint8{0, 2, 4, 6}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
