// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EtInvalid - -1]
	_ = x[EtEOF-0]
	_ = x[TtListComprehension-1]
	_ = x[TtNewline-2]
	_ = x[TtPrintStmt-3]
	_ = x[NtSource-4]
	_ = x[NtSource1-5]
	_ = x[NtStatement-6]
}

const _TokenType_name = "EtInvalidEtEOFTtListComprehensionTtNewlineTtPrintStmtNtSourceNtSource1NtStatement"

var _TokenType_index = [...]uint8{0, 9, 14, 33, 42, 53, 61, 70, 81}

func (i TokenType) String() string {
	i -= -1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
